### ISSUE TITLE
First deployment issue "Unable to find device path out of attempted paths"

### ISSUE THREAD

**Issue by lazyatom** [getkuby/kuby-linode#1]
Hi, I've been kicking the tyres of kuby trying to get a deployment of a [simple test application](https://github.com/lazyatom/kuby-test-app) working. I've tried on Digitalocean and seen a few issues, and I read that you were using Linode personally a bit more recently, so thought I'd try this too (this is actually better for me since I have existing servers via Linode). I should also say that I don't know much about k8s beyond the basic concepts. 

I'm seeing an error during my first deploy which I was hoping you might be able to help with. Here's the gist of the error(s) during deploying, trimmed for brevity:

```
[INFO][2020-10-27 10:33:29 +0000]	- ServiceAccount/kubytestapp-assets-sa (timeout: 30s)
[INFO][2020-10-27 10:33:29 +0000]	- ServiceAccount/kubytestapp-sa (timeout: 30s)
[INFO][2020-10-27 10:33:37 +0000]	Successfully deployed in 7.6s: ClusterIssuer/letsencrypt-production, ConfigMap/kubytestapp-assets-nginx-config, ConfigMap/kubytestapp-config, Ingress/kubytestapp-ingress, PersistentVolumeClaim/kubytestapp-assets, Postgres/kubytestapp-web-postgres, Postgres/kubytestapp-web-postgres, Secret/kubytestapp-registry-secret, Secret/kubytestapp-secrets, Secret/kubytestapp-web-postgres-secret, Secret/kubytestapp-web-postgres-secret, Service/kubytestapp-assets-svc, Service/kubytestapp-svc, ServiceAccount/kubytestapp-assets-sa, ServiceAccount/kubytestapp-sa
[INFO][2020-10-27 10:33:37 +0000]	Continuing to wait for: Deployment/kubytestapp-assets, Deployment/kubytestapp-web
[INFO][2020-10-27 10:34:09 +0000]	Still waiting for: Deployment/kubytestapp-assets, Deployment/kubytestapp-web
(... repeats a few times ...)
[ERROR][2020-10-27 10:37:53 +0000]	Deployment/kubytestapp-web failed to deploy after 263.9s
[INFO][2020-10-27 10:37:53 +0000]	Continuing to wait for: Deployment/kubytestapp-assets
(... repeats a few times ...)
[ERROR][2020-10-27 10:43:32 +0000]	Deployment/kubytestapp-assets rollout timed out after 603.2s
[INFO][2020-10-27 10:43:38 +0000]	
[INFO][2020-10-27 10:43:38 +0000]	------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2020-10-27 10:43:38 +0000]	Successfully deployed 15 resources, timed out waiting for 1 resource to deploy, and failed to deploy 1 resource
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	Successful resources
[FATAL][2020-10-27 10:43:38 +0000]	ClusterIssuer/letsencrypt-production              Exists
[FATAL][2020-10-27 10:43:38 +0000]	ConfigMap/kubytestapp-assets-nginx-config         Available
[FATAL][2020-10-27 10:43:38 +0000]	ConfigMap/kubytestapp-config                      Available
[FATAL][2020-10-27 10:43:38 +0000]	Ingress/kubytestapp-ingress                       Created
[FATAL][2020-10-27 10:43:38 +0000]	PersistentVolumeClaim/kubytestapp-assets          Bound
[FATAL][2020-10-27 10:43:38 +0000]	Postgres/kubytestapp-web-postgres                 Exists
[FATAL][2020-10-27 10:43:38 +0000]	Postgres/kubytestapp-web-postgres                 Exists
[FATAL][2020-10-27 10:43:38 +0000]	Secret/kubytestapp-registry-secret                Available
[FATAL][2020-10-27 10:43:38 +0000]	Secret/kubytestapp-secrets                        Available
[FATAL][2020-10-27 10:43:38 +0000]	Secret/kubytestapp-web-postgres-secret            Available
[FATAL][2020-10-27 10:43:38 +0000]	Secret/kubytestapp-web-postgres-secret            Available
[FATAL][2020-10-27 10:43:38 +0000]	Service/kubytestapp-assets-svc                    Selects at least 1 pod
[FATAL][2020-10-27 10:43:38 +0000]	Service/kubytestapp-svc                           Selects at least 1 pod
[FATAL][2020-10-27 10:43:38 +0000]	ServiceAccount/kubytestapp-assets-sa              Created
[FATAL][2020-10-27 10:43:38 +0000]	ServiceAccount/kubytestapp-sa                     Created
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	Deployment/kubytestapp-assets: TIMED OUT (progress deadline: 600s)
[FATAL][2020-10-27 10:43:38 +0000]	Timeout reason: ProgressDeadlineExceeded
[FATAL][2020-10-27 10:43:38 +0000]	Latest ReplicaSet: kubytestapp-assets-bc884b447
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	The following containers have not passed their readiness probes on at least one pod:
[FATAL][2020-10-27 10:43:38 +0000]	> kubytestapp-assets must respond with a good status code at '/500.html'
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	  - Final status: 1 replica, 1 updatedReplica, 1 unavailableReplica
[FATAL][2020-10-27 10:43:38 +0000]	  - Events (common success events excluded):
[FATAL][2020-10-27 10:43:38 +0000]	      [Deployment/kubytestapp-assets]	ScalingReplicaSet: Scaled up replica set kubytestapp-assets-bc884b447 to 1 (1 events)
[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-assets-bc884b447-z4d59]	SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-2a4e671af47a4796"  (1 events)
[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-assets-bc884b447-z4d59]	Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 404 (78 events)
[FATAL][2020-10-27 10:43:38 +0000]	  - Logs from container 'kubytestapp-assets' (last 25 lines shown):
[FATAL][2020-10-27 10:43:38 +0000]	      178.79.137.135 - - [27/Oct/2020:10:42:58 +0000] "GET /500.html HTTP/1.1" 404 143 "-" "kube-probe/1.18" "-"
(... repeats a few times ...)
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	Deployment/kubytestapp-web: FAILED
[FATAL][2020-10-27 10:43:38 +0000]	Latest ReplicaSet: kubytestapp-web-79ccd997bd
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	The following containers are in a state that is unlikely to be recoverable:
[FATAL][2020-10-27 10:43:38 +0000]	> kubytestapp-create-db: Crashing repeatedly (exit 1). See logs for more information.
[FATAL][2020-10-27 10:43:38 +0000]	
[FATAL][2020-10-27 10:43:38 +0000]	  - Final status: 1 replica, 1 updatedReplica, 1 unavailableReplica
[FATAL][2020-10-27 10:43:38 +0000]	  - Events (common success events excluded):
[FATAL][2020-10-27 10:43:38 +0000]	      [Deployment/kubytestapp-web]	ScalingReplicaSet: Scaled up replica set kubytestapp-web-79ccd997bd to 1 (1 events)
[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-web-79ccd997bd-56dh2]	SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-2a4e671af47a4796"  (1 events)
[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-web-79ccd997bd-56dh2]	FailedMount: MountVolume.MountDevice failed for volume "pvc-2a4e671af47a4796" : rpc error: code = Internal desc = Unable to find device path out of attempted paths: [/dev/disk/by-id/linode-pvc2a4e671af47a4796 /dev/disk/by-id/scsi-0Linode_Volume_pvc2a4e671af47a4796] (4 events)
[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-web-79ccd997bd-56dh2]	BackOff: Back-off restarting failed container (7 events)
[FATAL][2020-10-27 10:43:38 +0000]	  - Logs from container 'kubytestapp-web': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-27 10:43:38 +0000]	  - Logs from container 'kubytestapp-migrate-db': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-27 10:43:38 +0000]	  - Logs from container 'kubytestapp-copy-assets': None found. Please check your usual logging service (e.g. Splunk).
[FATAL][2020-10-27 10:43:38 +0000]	  - Logs from container 'kubytestapp-create-db' (last 25 lines shown):
[FATAL][2020-10-27 10:43:38 +0000]	      /usr/src/app/bundle/ruby/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
(... standard Rails backtrace you'd expect ...)
[FATAL][2020-10-27 10:43:38 +0000]	      (See full trace by running task with --trace)
```

I think the key line is this one:

`[FATAL][2020-10-27 10:43:38 +0000]	      [Pod/kubytestapp-web-79ccd997bd-56dh2]	FailedMount: MountVolume.MountDevice failed for volume "pvc-2a4e671af47a4796" : rpc error: code = Internal desc = Unable to find device path out of attempted paths: [/dev/disk/by-id/linode-pvc2a4e671af47a4796 /dev/disk/by-id/scsi-0Linode_Volume_pvc2a4e671af47a4796] (4 events)`

Clearly something that the web container needed to be mounted hasn't worked, and that's almost certainly why the `create_db` task failed (and likely why the assets didn't build either).

In the Linode cloud manager, I can see that volume `pvc2a4e671af47a4796` exists, and it's attached to node `lke12157-15105-5f97f2282942` (which is the only node in the k8s cluster). There's also a second volume which I can see is attached to the kubedb pod.

Running `bundle exec kuby -e production kubectl -- describe pods -n kubytestapp-production` I can see that the `pvc-2a4e671af47a4796` volume was successfully attached to the assets pod; [reading around the Linode forums](https://www.linode.com/community/questions/20010/deploying-postgres-databasa-with-csi-volumes) suggests that the error isn't unheard of, but it's not clear what the true cause is.

Any ideas?

**Comment by camertron** [comment]
@lazyatom oof that's not fun. Unfortunately I've never come across this particular error before. I think you're right in your identification of the problem, i.e. one of the volumes failed to mount. I noticed in the forum post you linked someone mentioned detaching and re-attaching the volume in the Linode web UI - have you tried that? I would guess that as soon as the volume is available, Kubernetes will "heal" and your site will come up as it should. You could also get in touch with Linode support, they're generally very helpful.

**Comment by lazyatom** [comment]
I did indeed try detaching and re-attaching, to no avail. I've also tried restarting the node, and even changing the root password so I can use the linode console to see what docker is doing on that machine. What I will say is that after all that poking around, the error reported by `describe nodes` has at least changed, to:

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2e9041f2746ce4967b6ea20f90de9ea2473d94c08da28e3bed0fbba5e1e6569d" network for pod "kubytestapp-assets-bc884b447-z4d59": networkPlugin cni failed to set up pod "kubytestapp-assets-bc884b447-z4d59_kubytestapp-production" network: error adding host side routes for interface: calie96fd0d571d, error: route (Ifindex: 22, Dst: 10.2.0.16/32, Scope: 253) already exists for an interface other than 'calie96fd0d571d'
```

I'll contact Linode and see what they say. What I don't understand though is that this is a super-basic Rails application (literally a newly generated Rails 6 application with a single controller), and brand new k8s cluster, so it seems likely that everyone else trying this on Linode will also hit this issue. I assume you've been building/tearing-down clusters as you've been testing things?

**Comment by lazyatom** [comment]
I believe I've solved this. The actual problem was that the "rewritten" database credentials in the docker image didn't match the ones that the Postgres instance was expecting. I'm not sure why this would've manifest as this particular error, but once I spotted that the Postgres database was rejecting connections, I realised that the database config rewriting is only changing the hostname, and not doing anything with the credentials. Fixing the credentials such that both `database.yml` _and_ `kuby.rb`'s `database` block shared the same data resulted in a successful deployment and all nodes starting.

Now I just have a cert-manager bug to resolve...

**Comment by camertron** [comment]
@lazyatom ahh ok nice, glad you were able to figure it out. While database creds issue could definitely cause issues, I too am skeptical it was the cause of the error message you received. I'd bet the real issue is because of the volume attachment issue being discussed in other threads. You may have just gotten lucky, i.e. Kubernetes probably scheduled the web pods to run on the same node as the asset server, so attaching the volume worked as expected.

**Comment by lazyatom** [comment]
Up until that point I'd always been deploying against a single-node cluster (and indeed, I'm not sure kuby can support multi-node clusters, on Linode at least -- getkuby/kuby-core#42). But who knows! 🤷

**Comment by camertron** [comment]
@lazyatom it definitely _should_ support multiple nodes, it's a bug that it doesn't 😏  Hoping to look into it later this week or maybe during the weekend.
